version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Berlin"
    assignees:
      - "m-radmacher"
    labels:
      - "dependencies"
